language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby-9.2
before_install:
  - yes | gem update --system --force
  - gem install bundler
gemfile:
  - gemfiles/minitest4.gemfile
  - gemfiles/minitest5.gemfile
  - gemfiles/test_unit_gem.gemfile
install:
  - bundle install
script:
  - bundle exec rake test
